#Qui impostiamo le configurazioni di base per i siteaccess
siteaccesses:
  devel:
    #Espressione regolare preferibilmente
    host_pattern: non_e_fatto_per_web
    file: development.yml

  test:
    #Espressione regolare preferibilmente
    host_pattern: non_e_fatto_per_web
    file: test.yml

  prod:
    #Espressione regolare preferibilmente
    host_pattern: non_e_fatto_per_web
    file: production.yml


#------------------------------------------------------------------
#                           SERVIZI
#------------------------------------------------------------------
services:

  #Si incarica delle operazioni I/O sul filesystem
  file_handler:
    class: FileHandlerService
    mandatory: true

  #Si incarica di salvare in cache qualche informazione
  #Dipende dal servizio "file_handler"
  file_caching:
    class: TimeIntervalService
    conf_alias: file_handler

  #Per scrivere nei log
  logger:
    class: LoggerService
    mandatory: true

  #Gestisce la visualizzazione degli errori - utile per sviluppo e test -
  #non dev'essere messo in prod
  error_handler:
    class: ErrorDebugHandlerService
    conf_alias: error_debug_handler
    mandatory: true

  #Per le connessioni ai DB tramite doctrine
  db_connection:
    class: DatabaseConnectionService
    conf_alias: database

  #Non sono sicuro se per questo progetto sarà utile un mailer
  #Ma si incarica del invio delle mail
  mailer:
    class: MailerService

  #Template Engine per la renderizzazione tramite tali
  template_engine:
    class: TemplateEngineService
    conf_alias: twig

  #Crea e salva Alias delle immagini a seconda le impostazioni YAML
  image_handler:
    class: ImageHandlerService\ImageHandler
    conf_alias: image_alias_handler

  #Si incarica del routing dell'applicazione
  router:
    class: RouterService
    mandatory: true

  #Gestisce i controller dell'applicazione
  controller_handler:
    class: ControllerResolverService
    mandatory: true

  #Per tutto ciò relativo al calcolo di periodi di tempo
  time_interval:
    class: TimeIntervalService
    conf_alias: fetch_articles_using